### ISSUE TITLE
Add further plan_types

### ISSUE THREAD

**Issue by Shen** [joachimdieterich/laravel-curriculum-adminlte3#124]
If I add a new Lern-/Arbeitsplat I get an error after clicking on it:

ErrorException
Trying to get property 'title' of non-object (View: [PATH]/laravel-curriculum-adminlte3/resources/views/plans/show.blade.php)
https://[URL]/plans/1

**Comment by joachimdieterich** [comment]
wip

**Comment by joachimdieterich** [comment]
Will be implemented with "Feature Request: Individual curricula #140"
