### ISSUE TITLE
Feature Request: Export curriculum

### ISSUE THREAD

**Issue by Shen** [joachimdieterich/laravel-curriculum-adminlte3#127]
You are able to import but not to export a curriculum. That makes little sense ;-)

**Comment by joachimdieterich** [comment]
You are right. The import exists for the old version of curriculum: https://github.com/joachimdieterich/curriculum
The export is still being implemented.

**Comment by Shen** [comment]
@joachimdieterich The export-feature does not work. Nothing happens if I click on "Export Curriculum"

**Comment by joachimdieterich** [comment]
You find the exported files under /storage/app/export
This is yet not documented. Reopen issue.
