### ISSUE TITLE
Feature Request: Adding Nextcloud/Owncloud as external resource

### ISSUE THREAD

**Issue by Shen** [joachimdieterich/laravel-curriculum-adminlte3#131]
It would be great to add Nextcloud/Owncloud as external resource. It would be nice if this could be configured via the school-admin menu (preset a nextcloud-server).

**Comment by joachimdieterich** [comment]
This is not planned, cause we use the internal filesystem/edusharing, but you can connect external filesystems like Amazon S3 out of the box. You will find the configuration file under` /config/filesystems.php` .
There are also some packages out there that can connect nextcloud or owncloud.

**Comment by Shen** [comment]
Some packages? Something like this? https://github.com/bahuma/oauth2-nextcloud
We (and a lot of other schools) use Nextcloud to save teaching materials there. A direct connection to the nextcloud-system would make processes much easier.
![nextcloud-connection](https://user-images.githubusercontent.com/81589/102935474-8285d180-44a6-11eb-94e4-474520d86d13.png)

**Comment by joachimdieterich** [comment]
There are ready to use packages to connect the nextcloud as storage. (e. g. https://github.com/jedlikowski/laravel-nextcloud)
