### ISSUE TITLE
Curricula: wrong breadcrumb navigation

### ISSUE THREAD

**Issue by Shen** [joachimdieterich/laravel-curriculum-adminlte3#134]
If you enter the curricula-section you see a breadcrumb navigation to Startseite and Curricula (that's fine). The link to curricula is not clickable.
![curriculum-breadcrumb1](https://user-images.githubusercontent.com/81589/102752924-a04e1c00-436a-11eb-9e92-c00ad2acdffc.png)
If you enter a curriculum you see a breadcrumb navigation to Startseite and the current curriculum. A link to curricula is missing. Also the link to the current curriculum should be named like the current curriculum.
![curriculum-breadcrumb2](https://user-images.githubusercontent.com/81589/102752925-a04e1c00-436a-11eb-892e-2c0c1bfb6611.png)
If you enter a curriculum-module you see a breadcrumb navigation to Startseite, current curriculum and details. A link to curricula is missing. The link to details is not clickable.
![curriculum-breadcrumb3](https://user-images.githubusercontent.com/81589/102752921-9fb58580-436a-11eb-81ed-c3cfd492f312.png)

**Comment by joachimdieterich** [comment]
The current page in the breadcrumb does not have to be clickable. 
There is a special feature in the breadcrumb for the curriculum view. The view can be called up as curriculum and course. 
Difference between curriculum and course-view: in the course-view the teacher sees the students and can set learning levels; students can assess themselves. If you are in the course-view, you can switch to the curriculum-view via the breadcrumb.

The paths to the curriculum/course-view can be different. Therefore, there are no superordinate levels in the breadcrumb. 

Suggestions for improvement are welcome

**Comment by Shen** [comment]
Maybe something like the "change role" feature in moodle?
![moodle-change-role](https://user-images.githubusercontent.com/81589/102788304-b7a8fb80-43a2-11eb-87a9-513a3d0e3b3c.png)
