### ISSUE TITLE
Feature Request: Benutzer: Status of enrollment should be visible

### ISSUE THREAD

**Issue by Shen** [joachimdieterich/laravel-curriculum-adminlte3#135]
The status of enrollment should be visible without clicking on user-details. There is no overview of who is enrolled in which roles and where.

**Comment by joachimdieterich** [comment]
A user can have multiple roles (multitenancy). The role can be different on every organization. 
With many users, loading the datasets into the datatable would take a very long time, as all organisational enrolments would have to be determined for each user.

**Comment by joachimdieterich** [comment]
Did some tests on this request. Queries would be much to timeconsuming and affecting the usability. A possible solution could be a role-filter.
