### ISSUE TITLE
Feature Request: Enhanced usermanagement (csv-import)

### ISSUE THREAD

**Issue by Shen** [joachimdieterich/laravel-curriculum-adminlte3#136]
A possibility to import multiple users via csv-file would be great.
An individual institution dependent unique-user-id should be added to make subsequent imports easier and to avoid duplicate accounts.

**Comment by joachimdieterich** [comment]
Steps to get this feature working: 
`composer update
composer dump-autoload'
Depending on usecase
'npm run production` or 'npm run development` or 'npm run watch`
