### ISSUE TITLE
Fächer: Where can I edit/add Fächer?

### ISSUE THREAD

**Issue by Shen** [joachimdieterich/laravel-curriculum-adminlte3#139]
In the user manual is written, that you can add/edit Fächer.
But I can't find a menu-item for this.

**Comment by joachimdieterich** [comment]
There is currently no option, as the subjects are prescribed by the country. 
This feature has yet to be implemented.

**Comment by Shen** [comment]
Okay, but where do you locate something like "Medienkompetenzrahmen"? There is no "fächerübergreifend".

**Comment by Shen** [comment]
@joachimdieterich 
Thank you! The short title is obligatory. With intent?
