### ISSUE TITLE
Lernzeitraum: new Lernzeiträume don't work (no courses listed)

### ISSUE THREAD

**Issue by Shen** [joachimdieterich/laravel-curriculum-adminlte3#142]
I added new Lerzeiträume. If I select "Schuljahr 2020/21" in a group, there are no courses listed. If I select the existing "Test", it works fine.
![lernzeiträume](https://user-images.githubusercontent.com/81589/102817083-619e7d00-43cf-11eb-9a71-9b71d1b048b5.png)
I cannot delete the Lernzeitraum "Test" even if it is not assigned to any group.

**Comment by joachimdieterich** [comment]
About the structure: 
Each group has a learning period. Groups (should) exist even if the group members are in a new group in a new school year. 
If a user has several learning periods, a 3rd pull-down menu appears in the menu on the left. There you can set the current learning period. 

A course is the combination of curriculum and group. To create a course, select the desired group(s) under` /groups`. Then select the desired curriculua at the bottom and click on "Enrol to curriculum". 

I could not reproduce the error with the deletion. Is there an error in telescope `[localhost]/telescope`?

**Comment by Shen** [comment]
> About the structure:
> Each group has a learning period. Groups (should) exist even if the group members are in a new group in a new school year.
> If a user has several learning periods, a 3rd pull-down menu appears in the menu on the left. There you can set the current learning period.

I have added the learning period "Schuljahr 2020/21".
![group](https://user-images.githubusercontent.com/81589/102829388-46d80280-43e7-11eb-8a06-c0b28c3c1553.png)


> A course is the combination of curriculum and group. To create a course, select the desired group(s) under` /groups`. Then select the desired curriculua at the bottom and click on "Enrol to curriculum".

I enrolled to "Medienkompetenzrahmen NRW" but there is no course.
![group-learning_periode-course](https://user-images.githubusercontent.com/81589/102828934-36735800-43e6-11eb-9ea9-c6e534a57005.png)
 
> I could not reproduce the error with the deletion. Is there an error in telescope `[localhost]/telescope`?

`[localhost]/telescope` shows 403?

**Comment by joachimdieterich** [comment]
Have you enroled yourself into the group "jg10"? (Benutzerverwaltung > choose User(s)  > enrol to group jg10. 
You only see Courses in "your" Coursemenu if you are enroled.

The `/telescope` route is available for administrators, whose email-adress is entered in the gate function in` laravel-curriculum-adminlte3/app/Providers/TelescopeServiceProvider.php `:
```
protected function gate()
{
      Gate::define('viewTelescope', function ($user) {
         return in_array($user->email, [        
             'admin@curriculumonline.de'
         ])
     });
}
```

**Comment by Shen** [comment]
> Have you enroled yourself into the group "jg10"? (Benutzerverwaltung > choose User(s) > enrol to group jg10.
> You only see Courses in "your" Coursemenu if you are enroled.
Yes, I have enroled myself to the group jg10.
![admin-gruppen](https://user-images.githubusercontent.com/81589/102931784-4c911f00-449f-11eb-84f0-aa238c912ec3.png)

I don't know if it is relevant but if you can see, the admin role administrator@xxx-schule.de is listed twice instead of administrator@curriculumonline and administrator@xxx-schule

**Comment by Shen** [comment]
> I could not reproduce the error with the deletion. Is there an error in telescope `[localhost]/telescope`?

`"message": "SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`curriculum`.`users`, CONSTRAINT `users_current_period_id_foreign` FOREIGN KEY (`current_period_id`) REFERENCES `periods` (`id`)) (SQL: delete from `periods` where `id` = 1)",
"exception": "Illuminate\Database\QueryException",
"file": "/var/www/curriculum/htdocs/laravel-curriculum-adminlte3/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
"line": 669,`

**Comment by joachimdieterich** [comment]
error seems to be fixed
