### ISSUE TITLE
Seeding only missing tables

### ISSUE THREAD

**Issue by michaellass** [joachimdieterich/laravel-curriculum-adminlte3#145]
I'm unsure if there is a proper update procedure or if the database currently needs to be re-initialized when the database layout is changed.

To update, I currently run the following steps:
* git pull
* composer install --no-dev
* npm install
* npm run production
* php artisan migrate

The last command will run migrations to change the database scheme. However, no seeding is done so new tables are not filled with initial values. Running `php artisan migrate --seed` will attempt to re-seed existing tables and fail due to duplicate unique keys.

Is there a way to seed only new or missing tables? However, that would still leave situations like https://github.com/joachimdieterich/laravel-curriculum-adminlte3/commit/a9965f0294375d6104b9885621aa3cdc30dba53f#diff-3549b0028b75d981cdda2e573e9cb49dedc200185876df299f912b79f69dabd8 where existing tables need to be extended by entries.

**Comment by joachimdieterich** [comment]
If there are new migrations you could just do a `php artisan migrate`. 
If I added an field to an existing table like on contents (order_id) there is an extra migration:` laravel-curriculum-adminlte3/database/migrations/2020_12_05_182817_add_order_id_to_content_subscriptions_table.php 
` 
The order_id has a default value of `0`. If an user order an entry all related values will be set.

If you want to do a delete existing data to prevent errors you can do a `php artisan migrate:fresh --seed`. **Attention, all data in the database will be deleted.**

**Comment by michaellass** [comment]
Good to know that a normal `migrate` should be sufficient on updating. And the `migrate:fresh` will be handy during early testing. Thanks!
