### ISSUE TITLE
Guest-Role: Error 500 when clicking "Logbücher" is still not fixed

### ISSUE THREAD

**Issue by Shen** [joachimdieterich/laravel-curriculum-adminlte3#147]
This issue is still not fixed. After re-initializing the database, the `permission_role` table is filled accordingly. The `Guest` role has only permissions `curriculum_show` and `navigator_show`. However, after login as Guest, there is still the logbook menu item and clicking on it still leads to the exception.

_Originally posted by @michaellass in https://github.com/joachimdieterich/laravel-curriculum-adminlte3/issues/123#issuecomment-749513433_

**Comment by joachimdieterich** [comment]
Can you check if it's a caching issue?

The Logbook can be accessed over the dashboard ([permissioncheck](https://github.com/joachimdieterich/laravel-curriculum-adminlte3/blob/6294d4804f91e7d612347fdd4d72ab6682c25e98/resources/views/home.blade.php#L23))or the menu ([permissioncheck](https://github.com/joachimdieterich/laravel-curriculum-adminlte3/blob/6294d4804f91e7d612347fdd4d72ab6682c25e98/resources/views/partials/menu.blade.php#L76)). 

Try a `php artisan cache:clear` and clear the browser cache.

**Comment by michaellass** [comment]
I had checked the browser cache but wasn't aware of the application cache. `php artisan cache:clear` did the trick. I guess it's a good idea to run this on every update.
