### ISSUE TITLE
Curricula-Descriptions are not shown

### ISSUE THREAD

**Issue by Shen** [joachimdieterich/laravel-curriculum-adminlte3#150]
**Describe the bug**
Curricula-Descriptions are not shown

**To Reproduce**
1. Go to 'Curricula'
2. Click on an existing Curriculum (or create a new one)
3. Click on "add module"
4. Enter title and description and save.
5. Title is and description is not shown in the module-box.

**Expected behavior**
Title and description is shown in the module-box.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Opera/Firefox
 - Version 73/84

**Additional context**
I've cleared caches already.

**Comment by Shen** [comment]
When I click on the module box currently I get a blank page (no error in telescope).

I understand that you want to have a very clear layout. However, in order to evaluate a competence, it is necessary to see the details. A page change including a complete page reload disturbs the workflow. Maybe some kind of box extension would be possible, so that you could expand additional information via a click within the box?

**Comment by joachimdieterich** [comment]
Which endpoint is shown in your browser (on that blank page). 

We had the description in the old version as modal, which could be opened without going to detail page. 
The problem there was, that it didn't work out on mobile devices. 

Another option would be, that you can evaluate competences in the detail view.

**Comment by joachimdieterich** [comment]
This issue seems to be fixed
