### ISSUE TITLE
tinyMCE: creating a link with the option 'open in new tab' doesn't work

### ISSUE THREAD

**Issue by alexanderlang1al** [joachimdieterich/laravel-curriculum-adminlte3#532]
the link will still be opened in the current tab

**Comment by alexanderlang1al** [comment]
will be fixed in new version

**Comment by joachimdieterich** [comment]
The reason was the dompurifier. 
The problem for the kanbans and contents was solved by checking/changing the desired field in the model under $casts when saving and retrieving with 
`‘description’ => CleanHtml::class`
